server.port: 8089
spring:
  application.name: search-indexer-service
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8081
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.energypal.common.event
management.endpoints.web.exposure.include: health,info
